
mm_config_tools.settings_form:
  path: '/admin/config/mm_config_tools/settings'
  defaults:
    _form: '\Drupal\mm_config_tools\Form\SettingsForm'
    _title: 'SettingsForm'
  requirements:
    _permission: 'access administration pages'
  options:
    _admin_route: TRUE

